name: 5VpulseOS APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kivy/buildozer:latest
      options: --privileged
    steps:
    - uses: actions/checkout@v4

    - name: Build APK
      run: |
        buildozer -v android debug
      timeout-minutes: 40

    - uses: actions/upload-artifact@v4
      with:
        name: 5VpulseOS-APK
        path: bin/*.apk
