name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: stable
        env:
          ANDROID_SDK_ROOT: /home/runner/.buildozer/android/platform/android-sdk
      - uses: actions/upload-artifact@v4
        with:
          name: origenos-apk
          path: ${{ steps.buildozer.outputs.filename }}
